backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "notes"
    label: "Notes"
    label_singular: "Notes"
    folder: "notes"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Updated", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
